### ISSUE TITLE
New diffusers version breaks an import for image-to-3D

### ISSUE THREAD

**Issue by johnowhitaker** [dreamgaussian/dreamgaussian#1]
See https://github.com/huggingface/diffusers/issues/5025
They've moved randn_tensor, which causes an error if using the latest diffusers version. A possible fix is to edit zero123.py and change the import:
```python
# from diffusers.utils import deprecate, is_accelerate_available, logging, randn_tensor
from diffusers.utils import deprecate, is_accelerate_available, logging
from diffusers.utils.torch_utils import randn_tensor
```
Might need a version check for people on older diffusers, or just to copy the function definition in and avoid the issue that way.

Anyway, great work on this! I can't wait to start experimenting more. Well done :)

**Comment by ashawkey** [comment]
@johnowhitaker Thanks! This has been fixed in https://github.com/dreamgaussian/dreamgaussian/commit/a119fc11295b5869a0b48816ea3b3be5824c285d

**Comment by johnowhitaker** [comment]
That was quick :) Thanks
