### ISSUE TITLE
After running git pull "e932f2cf5020c8bdb8c9128175788aeb9338a718" I started seeing the error. ImportError: DLL load failed while importing _C

### ISSUE THREAD

**Issue by ptyogi** [dreamgaussian/dreamgaussian#100]
Hello.
After running git pull "e932f2cf5020c8bdb8c9128175788aeb9338a718" I started seeing the error. what is the reason?
```
(DreamGaussian) C:\Stable_Diffusion\dream>python main.py --config configs/image.yaml input=data/ghost_rgba.png save_path=ghost
Traceback (most recent call last):
  File "C:\Stable_Diffusion\dream\main.py", line 14, in <module>
    from gs_renderer import Renderer, MiniCam
  File "C:\Stable_Diffusion\dream\gs_renderer.py", line 10, in <module>
    from diff_gaussian_rasterization import (
  File "C:\Users\haijin\miniconda3\envs\DreamGaussian\lib\site-packages\diff_gaussian_rasterization\__init__.py", line 15, in <module>
    from . import _C
ImportError: DLL load failed while importing _C: 指定されたプロシージャが見つかりません。
``` 
![2023-12-22_185855](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/2bbaacd8-aa84-480c-a32d-463dab7fd898)
![2023-12-22_185904](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/28aa3e8b-d63a-4ac7-9bf9-9e3cdc040ff2)
![2023-12-22_185911](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/a527f22e-863e-4cdd-b56a-5bf0579f1572)

**Comment by ashawkey** [comment]
@ptyogi Hi, it seems you installed a new torch version. You may try to recompile the cuda extensions:
```bash
pip install ./diff-gaussian-rasterization
pip install ./simple-knn
```

**Comment by ptyogi** [comment]
> @ptyogi Hi, it seems you installed a new torch version. You may try to recompile the cuda extensions:
> 
> ```shell
> pip install ./diff-gaussian-rasterization
> pip install ./simple-knn
> ```
thank you!
It worked fine.
thank you very much.
