### ISSUE TITLE
loss setting

### ISSUE THREAD

**Issue by Dumeowmeow** [dreamgaussian/dreamgaussian#157]
I can't understand the way the loss is set up in zero123_utils.py,line 170
![DTFDWZSS@%HGYU3)AV3ZWVH](https://github.com/dreamgaussian/dreamgaussian/assets/99797884/e306d329-2191-4ba5-9f8d-dfaebcf7cc99)
I think the 'grad' is the SDS loss, why call it grad and set loss in this way?

**Comment by xiaoyaolovlife** [comment]
Same question

**Comment by Dumeowmeow** [comment]
> Same question

Maybe this blog can help you: https://zhuanlan.zhihu.com/p/687684435

**Comment by xiaoyaolovlife** [comment]
Many thanks！It helps me a lot！But I have another question
![image](https://github.com/user-attachments/assets/45ccfafe-0c93-4251-b05c-115ed4f37146)
Why set denoising step==1？

**Comment by xiaoyaolovlife** [comment]
这是unet内部有循环去噪t次的过程嘛（是的话能否帮忙提供个源码链接，去噪t次的话是把每次预测的噪声求和作为noise_pred的值嘛）？还是算法本身只需要预测第t轮加入的噪声，这块一直不是很懂

"Does this UNet internally perform a loop to denoise 't' times (if yes, could you please provide a link to the source code? If it denoises 't' times, does it sum up the noise predicted in each iteration to use as the value for noise_pred)? Or does the algorithm itself only need to predict the noise added in the 't'-th round? I've always been a bit confused about this part."

**Comment by Dumeowmeow** [comment]
> 这是unet内部有循环去噪t次的过程嘛（是的话能否帮忙提供个源码链接，去噪t次的话是把每次预测的噪声求和作为noise_pred的值嘛）？还是算法本身只需要预测第t轮加入的噪声，这块一直不是很懂
> 
> "Does this UNet internally perform a loop to denoise 't' times (if yes, could you please provide a link to the source code? If it denoises 't' times, does it sum up the noise predicted in each iteration to use as the value for noise_pred)? Or does the algorithm itself only need to predict the noise added in the 't'-th round? I've always been a bit confused about this part."

不是，给定xt和t，利用unet预测之前加的噪声（从x0直接一步到位加噪到xt的那个噪声）。还有就是，diffusers官方代码的循环去噪都是在unet外面进行的，unet只负责预测一步到位的噪声（也就是直接把这个噪声减去是可以直接得到干净x0的，但是不能这么做），原因扩散模型的推导中需要遵循马尔可夫链的性质。

**Comment by xiaoyaolovlife** [comment]
非常谢谢您，但当我在我的任务上想验证每次SDS损失蒸馏出来的结果时可视化出现了很奇怪的结果，这里暂时以stable diffusion+针对任务设定的prompt举例
![image](https://github.com/user-attachments/assets/b28fac65-d3ad-43db-be4c-ff306c5ac282)
![image](https://github.com/user-attachments/assets/1c9ec2df-1cfe-4f35-a94d-01a1b1dc58a7)
![image](https://github.com/user-attachments/assets/432ba660-081b-49e5-9d2f-627034c1871b)
我的理解是每次SDS的grad代表我希望优化的像素区域，target代表优化后的样子。预期应该是随着优化的进行，grad整体逐渐呈非常浅的白色，target愈发接近未加噪前的latent。可否帮忙指导下是哪里出了问题，感激不尽！！
