### ISSUE TITLE
Failed to build diff_gaussian_rasterization

### ISSUE THREAD

**Issue by Huangkangxian** [dreamgaussian/dreamgaussian#163]
When I run pip install ./diff-gaussian-rasterization,
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Processing ./diff-gaussian-rasterization
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-38
      creating build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization
      running build_ext
      /home/zhujian_test/.conda/envs/dreamgs/lib/python3.8/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no g++ version bounds defined for CUDA version 12.1
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'diff_gaussian_rasterization._C' extension
      creating /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38
      creating /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer
      Emitting ninja build file /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
      1.11.1.git.kitware.jobserver-1
      g++ -pthread -B /home/zhujian_test/.conda/envs/dreamgs/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/zhujian_test/.conda/envs/dreamgs/include -fPIC -O2 -isystem /home/zhujian_test/.conda/envs/dreamgs/include -pthread -B /home/zhujian_test/.conda/envs/dreamgs/compiler_compat -shared /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/backward.o /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/forward.o /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/ext.o /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/rasterize_points.o -L/home/zhujian_test/.conda/envs/dreamgs/lib/python3.8/site-packages/torch/lib -L/home/zhujian_test/cuda12.1/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-38/diff_gaussian_rasterization/_C.cpython-38-x86_64-linux-gnu.so
      g++: error: /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/backward.o: No such file or directory
      g++: error: /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/forward.o: No such file or directory
      g++: error: /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/cuda_rasterizer/rasterizer_impl.o: No such file or directory
      g++: error: /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/ext.o: No such file or directory
      g++: error: /home/zhujian_test/1-hkx/Code/dreamgaussian-main/diff-gaussian-rasterization/build/temp.linux-x86_64-cpython-38/rasterize_points.o: No such file or directory
      error: command '/home/zhujian_test/gcc/bin/g++' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gaussian_rasterization)

Could anybody help?Thanks a lot!

**Comment by WRY0627** [comment]
hi, may I ask if you have solved this problem? I have also encountered the same error and I am not sure how to solve it! Thanks!!!!
