### ISSUE TITLE
GPU OOM error

### ISSUE THREAD

**Issue by fatbao55** [dreamgaussian/dreamgaussian#21]
Hi authors, 

Thanks for the great work! I encountered OOM issues when running with a 24GB GPU. 

This is my command:
`python main.py --config configs/image.yaml input=data/anya_rgba.png save_path=output/anya gui=False force_cuda_rast=True`

It occurs randomly at this line of code:
`num_rendered, color, depth, alpha, radii, geomBuffer, binningBuffer, imgBuffer = _C.rasterize_gaussians(*args)`

and throws this error:
`CUDA out of memory. Tried to allocate 35.79 GiB. GPU 0 has a total capacty of 23.65 GiB of which 20.13 GiB is free. Including non-PyTorch memory, this process has 2.71 GiB memory in use. Of the allocated memory 2.35 GiB is allocated by PyTorch, and 28.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`

I am using a bigger GPU memory than one of the tested device (3070) and therefore OOM error should not occur. I was wondering if you have any advice on this?

**Comment by ashawkey** [comment]
@fatbao55 Hi, it also states `Including non-PyTorch memory, this process has 2.71 GiB memory in use`, while the program needs ~8GB to run. Could you turn off the other processes and try again?

**Comment by ashawkey** [comment]
this seems really strange... could you give more details on the environment, like OS, pytorch & CUDA version?
