### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Subin-Kim46** [dreamgaussian/dreamgaussian#24]
Hi,

Thank you for your excellent investigation.
I got some error. I think it's not match cuda version and gcc version.

Like this error
https://github.com/mapillary/inplace_abn/issues/106#issuecomment-475460496

My version is cuda 11.6 and gcc version 9.4.0
Can you tell me the version you used?

[INFO] load image from data/AU/w1_rgba.png...
Number of points at initialisation :  5000
[INFO] loading zero123...
Loading pipeline components...: 100%|█████████████████████████████████████████████████████| 6/6 [00:00<00:00,  7.16it/s]
[INFO] loaded zero123!
100%|█████████████████████████████████████████████████████████████████████████████████| 500/500 [00:54<00:00,  9.25it/s]
[INFO] save model to logs/w1_model.ply.
/home/sbkim/dreamgaussian/dream_venv/lib/python3.8/site-packages/torch/functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ../aten/src/ATen/native/TensorShape.cpp:2894.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/sbkim/dreamgaussian/dream_venv/lib/python3.8/site-packages/varname/utils.py:447: UsingExecWarning: 'pure_eval' is not installed. Using 'eval' to get the function that calls 'argname'. Try calling it using a variable reference to the function, or passing the function to 'argname' explicitly.
  warnings.warn(
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0∈ [0.0, 65.49642181396484] μ = 0.1503143310546875 σ =
1.5049272775650024
[INFO] mesh cleaning: (15938, 3) --> (9009, 3), (31868, 3) --> (18014, 3)
[INFO] marching cubes result: torch.Size([9009, 3]) (-0.689032793045044-0.6991069912910461), torch.Size([18014, 3])
[INFO] unwrap uv...
Traceback (most recent call last):
  File "/home/sbkim/dreamgaussian/dream_venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

...

fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Comment by ashawkey** [comment]
@Subin-Kim46 Hi, this is caused by an NVIDIA driver installation without opengl. You can either reinstall the driver or try adding `force_cuda_rast=True` to the command.

**Comment by lyk412** [comment]
> @Subin-Kim46 Hi, this is caused by an NVIDIA driver installation without opengl. You can either reinstall the driver or try adding `force_cuda_rast=True` to the command.

Hi. when I run the command `python -m kiui.render logs/name.obj --save_video name.mp4 --wogui` or` python -m kiui.render logs/name.obj --save images/name/ --wogui`, I met the problem mentioned aboved. I tried to add  `force_cuda_rast=True` at the end of the command, but got the error: 

> render.py: error: unrecognized arguments: force_cuda_rast=True

How can I run it successfully?

**Comment by ashawkey** [comment]
For `renderer.py`, you need to append `--force_cuda_rast`.

**Comment by lyk412** [comment]
> For `renderer.py`, you need to append `--force_cuda_rast`.

It works! Thank you so much for such a timely reply!

**Comment by HuntZhaozq** [comment]
> > For `renderer.py`, you need to append `--force_cuda_rast`.
> 
> It works! Thank you so much for such a timely reply!

 @lyk412  Hello, I have the same problem when using text-to-3D. Where to append --force_cuda_rast to renderer.py. I can not find this .py file.

**Comment by HuntZhaozq** [comment]
> > For `renderer.py`, you need to append `--force_cuda_rast`.
> 
> It works! Thank you so much for such a timely reply!

@ashawkey @lyk412  Hello, I have the same problem when using text-to-3D. Where to append --force_cuda_rast to renderer.py. I can not find this .py file.

**Comment by lixinhaiyk** [comment]
> > For `renderer.py`, you need to append `--force_cuda_rast`.
> 
> It works! Thank you so much for such a timely reply!

hi bro i met the same problem when running` python -m kiui.render logs/name.obj --save_video name.mp4 --wogui`，also i could not find the file renderer.py you referred to.
