### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by tyhuang0428** [dreamgaussian/dreamgaussian#27]
Thank you for sharing your great work! I noticed that you mentioned rigged animation in your paper, but I didn't find its implementation details. How do you animate the 3D output? Can you share the animation pipeline? Thank you very much.

**Comment by ashawkey** [comment]
@tyhuang0428 Hi, you can simply upload the exported obj & mlt & png (zipped) to https://www.mixamo.com/ for animation.

**Comment by tyhuang0428** [comment]
Thanks. It's pretty cool!
