### ISSUE TITLE
🦒 colab

### ISSUE THREAD

**Issue by camenduru** [dreamgaussian/dreamgaussian#3]
Thanks for the project ❤️ I made a colab. 🥳 I hope you like it. https://github.com/camenduru/dreamgaussian-colab

**Comment by ashawkey** [comment]
Wow thanks! I'm working on a image-to-3D colab notebook, maybe we can add it there.

**Comment by ashawkey** [comment]
@camenduru I'm done with that, thanks for the pre-built wheels! 
https://colab.research.google.com/drive/1sLpYmmLS209-e5eHgcuqdryFRRO6ZhFS?usp=sharing

**Comment by camenduru** [comment]
I added the image-to-3D colab notebook 🥳 Thanks ❤

**Comment by zeak6464** [comment]
Image-to-3D colab demo has issues 

![image](https://github.com/dreamgaussian/dreamgaussian/assets/2738141/6cf0b5a5-a8cc-4113-85bd-c1d02f16d202)

**Comment by camenduru** [comment]
Please use this link for reporting colab-related issues: https://github.com/camenduru/dreamgaussian-colab/issues
