### ISSUE TITLE
Use the example prompt in the paper but got unsatisfied results

### ISSUE THREAD

**Issue by Sutongtong233** [dreamgaussian/dreamgaussian#33]
Hi, I have tried text-to-3D pipeline and used the prompt "a small saguaro cactus planted in a clay pot", the results are not satisfactory：
Stage 1: ![image](https://github.com/dreamgaussian/dreamgaussian/assets/56153611/09875051-2832-4a38-a568-f98cfcab27f4)
Stage 2: ![image](https://github.com/dreamgaussian/dreamgaussian/assets/56153611/30f8be1d-93ad-4b67-863660f2595cdc30)
I did not modify any configuration. Have you ever encountered the same problem？Thanks

**Comment by ashawkey** [comment]
@Sutongtong233 Hi, current text-to-3d results maybe unstable, and you could try training with different seeds. We are expecting to improve it with recent multi-view diffusion models.

**Comment by Sutongtong233** [comment]
Thank you for your response; I did find that the stability of image-to-3D is much better.
