### ISSUE TITLE
if colab fail, then ...

### ISSUE THREAD

**Issue by yuedajiong** [dreamgaussian/dreamgaussian#42]
main.py:
    line 506:  str(self.opt.save_path)
main2.py:
   line 660:  str(opt.save_path)

**Comment by ashawkey** [comment]
@yuedajiong I guess it's the uploaded filename only containing numbers, please try to rename it like `test.png` before uploading.

**Comment by yuedajiong** [comment]
@ashawkey 
yes!

modify filename OR str(save_path).

**Comment by yuedajiong** [comment]
N/A
