### ISSUE TITLE
Question: Would testing on an 8GB VRAM (specifically RTX 2070 Super) work?

### ISSUE THREAD

**Issue by oliVRqin** [dreamgaussian/dreamgaussian#52]
Haven't tested this yet, but it seems like the requirements GPU-wise could use a 3070, which I believe has 8GB VRAM. Would testing on this also work on an RTX 2070 Super (also has 8 VRAM)?

**Comment by oliVRqin** [comment]
cc @ashawkey if you have the time! This is super cool btw

**Comment by leviathandragonflyer** [comment]
my 2080 laptop works fine, gens in a few minutes each. 2070 might be slower or faster depending on whether a laptop or desktop variant, but it should work.

**Comment by oliVRqin** [comment]
Yeah, seems like the 2070 super worked. Thanks!
