### ISSUE TITLE
how to download the sd model and place local

### ISSUE THREAD

**Issue by HuntZhaozq** [dreamgaussian/dreamgaussian#54]
My linux system can not connect to huggingface.co. How to download the SD model and then place on the local folder? Which folder should I place the SD model.

**Comment by ashawkey** [comment]
@HuntZhaozq Hi, you may refer to diffusers for local checkpoint, or try using proxy for huggingface.

**Comment by HuntZhaozq** [comment]
Are there any materials for reference of diffusers for local checkpoint?  Please have a share. I am a new guy.

**Comment by HuntZhaozq** [comment]
@ashawkey Are there any materials for reference of diffusers for local checkpoint? Please have a share. I am a new guy.

**Comment by HuntZhaozq** [comment]
I run successfully refering to https://huggingface.co/docs/diffusers/using-diffusers/loading.
