### ISSUE TITLE
zero123plus support?

### ISSUE THREAD

**Issue by Ratinod** [dreamgaussian/dreamgaussian#56]
Can generate additional (6) images for other camera angles. 
https://github.com/SUDO-AI-3D/zero123plus

**Comment by ashawkey** [comment]
@Ratinod Hi, they only support rendering 6 fixed views, which is not compatible with our pipeline.

**Comment by Ratinod** [comment]
Instant-NGP, to my surprise, is able to generate a model using only 7 images. But the result is not ideal.
https://github.com/SUDO-AI-3D/zero123plus/issues/11#issuecomment-1781951276

It's a shame that this can't be added to the existing pipeline to produce more detailed final results of the non-visible parts of the image.
