### ISSUE TITLE
How to make time count and visualize?

### ISSUE THREAD

**Issue by ALEEEHU** [dreamgaussian/dreamgaussian#67]
May I ask how to make time count and visualize at the same time? 

The effect is just as your reference video shows.

https://github.com/dreamgaussian/dreamgaussian/assets/57009216/6396a546-66ce-4fca-955d-135123aeec8b

**Comment by ashawkey** [comment]
@ALEEEHU Hi, you'll need another timer when running the GUI. I just record the screen and add a timer later (see https://github.com/ashawkey/made-in-heaven-timer).

**Comment by ALEEEHU** [comment]
@ashawkey What about the visualization? Can I run the main.py to get this visualization effect?

**Comment by ALEEEHU** [comment]
More specifically, how does this optimization progress visualization to be made?
![image](https://github.com/dreamgaussian/dreamgaussian/assets/57009216/e90b0427-ab18-471b-9324-22da56655820)

**Comment by ashawkey** [comment]
Yes, just run with `gui=True` so you can visualize this optimization progress.

**Comment by ALEEEHU** [comment]
@ashawkey Thanks for your reply! But my current circumstance is that I connect the server to run code without display. So based on this situation, how can I visualize the optimization progress?

**Comment by ashawkey** [comment]
You'll need to modify the code to save some images during training in this case.

**Comment by ALEEEHU** [comment]
@ashawkey Thanks! I will have a try.
