### ISSUE TITLE
pip install ./diff-gaussian-rasterization -> Torch not found =/

### ISSUE THREAD

**Issue by pyjacques** [dreamgaussian/dreamgaussian#73]
Issue installing dreamgaussian at this step 3 `pip install ./diff-gaussian-rasterization`

> C:\Users\pierr\pinokio\api\dreamgaussian.git>pip install ./diff-gaussian-rasterization
> Processing c:\users\pierr\pinokio\api\dreamgaussian.git\diff-gaussian-rasterization
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Traceback (most recent call last):
>         File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-u3k1kgyt\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-u3k1kgyt\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-u3k1kgyt\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>         File "C:\Users\pierr\AppData\Local\Temp\pip-build-env-u3k1kgyt\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 13, in <module>
>       ModuleNotFoundError: No module named 'torch'
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

Working under Win 11 + RTX 3090 + Python 3.11.5 + Cuda 11.8 (gaussian splatting working aside normally)

PyTorch already installed correctly via 
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

Tested :
> >>> import torch
> >>> torch.cuda.is_available()
> True

Any suggestion please ?

**Comment by kahkeng** [comment]
Try running this first: `pip install wheel`, that helped for me on Linux.

**Comment by pyjacques** [comment]
Worked ! Thanks a lot @kahkeng =)
