### ISSUE TITLE
Image to 3D Colab Issues

### ISSUE THREAD

**Issue by MilesTheProwler** [dreamgaussian/dreamgaussian#8]
Hi, I got this error when I training in google colab ( Image to 3D ) 

![image](https://github.com/dreamgaussian/dreamgaussian/assets/134680400/f141c44e-1711-4146-9aaa-3d28d2b74cde)

**Comment by ashawkey** [comment]
@MilesTheProwler Hi, I guess this is because the uploaded image name is just a number (like 1.jpg), you could try renaming it with a string (like example.jpg) to avoid this casting problem for now.
