### ISSUE TITLE
[F glutil.cpp:338] eglInitialize() failed Aborted (core dumped)

### ISSUE THREAD

**Issue by digbangbang** [dreamgaussian/dreamgaussian#87]
[INFO] mesh cleaning: (24964, 3) --> (12312, 3), (49920, 3) --> (24620, 3)
[INFO] marching cubes result: torch.Size([12312, 3]) (-0.693241536617279-0.6783909201622009), torch.Size([24620, 3])
[INFO] unwrap uv...
[F glutil.cpp:338] eglInitialize() failed
Aborted (core dumped)

Hi, I met this problem when python main.py. What's going on here? How can I address this problem?

**Comment by digbangbang** [comment]
I fixed the problem when I change the image.yaml's force_cuda_rast: False to True.

**Comment by haoz19** [comment]
> I fixed the problem when I change the image.yaml's force_cuda_rast: False to True.

You are amazing! How can you find that!!!!
