### ISSUE TITLE
An error occurs after creating "icecream_model.ply".AttributeError: module 'pymeshlab' has no attribute 'Percentage'

### ISSUE THREAD

**Issue by ptyogi** [dreamgaussian/dreamgaussian#94]
An error occurs after creating "icecream_model.ply".
AttributeError: module 'pymeshlab' has no attribute 'Percentage' is displayed.
It doesn't change even if I change the version of pymeshlab.
I would like to know the cause.

(DreamGaussian) C:\Stable_Diffusion\dream>python main.py --config configs/text02.yaml prompt="a photo of an icecream" save_path=icecream
Number of points at initialisation :  5000
[INFO] loading SD...
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [00:01<00:00,  4.57it/s]
[INFO] loaded SD!
100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:43<00:00,  1.15it/s]
[INFO] save model to logs\icecream_model.ply.
C:\Users\haijin\miniconda3\envs\DreamGaussian\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\cb\pytorch_1000000000000\work\aten\src\ATen\native\TensorShape.cpp:3527.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Tensor occ torch.Size([128, 128, 128]) torch.float32 cuda:0 ∈ [0.0, 4.10744571685791] μ = 0.1224011555314064 σ =
0.35269248485565186
Traceback (most recent call last):
  File "C:\Stable_Diffusion\dream\main.py", line 902, in <module>
    gui.train(opt.iters)
  File "C:\Stable_Diffusion\dream\main.py", line 883, in train
    self.save_model(mode='geo+tex')
  File "C:\Users\haijin\miniconda3\envs\DreamGaussian\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Stable_Diffusion\dream\main.py", line 399, in save_model
    mesh = self.renderer.gaussians.extract_mesh(path, self.opt.density_thresh)
  File "C:\Stable_Diffusion\dream\gs_renderer.py", line 309, in extract_mesh
    vertices, triangles = clean_mesh(vertices, triangles, remesh=True, remesh_size=0.015)
  File "C:\Stable_Diffusion\dream\mesh_utils.py", line 113, in clean_mesh
    threshold=pml.Percentage(v_pct)
AttributeError: module 'pymeshlab' has no attribute 'Percentage'
![2023-12-13_153816](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/5b8989cd-660f-4180-8d5a-5318316c24e7)
![2023-12-13_153826](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/dd769e03-9a60-4a7c-b04d-810ef9cba37a)
![2023-12-13_153834](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/9baab507-af4c-4f9a-b6d9-794910a6075a)

**Comment by HaoZhang990127** [comment]
You can use the old version of pymeshlab, by using `pip install ==2022.2.post4` common to solve this problem

**Comment by ptyogi** [comment]
> `pip install ==2022.2.post4`この問題を解決するには、common を使用して古いバージョンの pymeshlab を使用できます。

thank you for your reply.
The version has been changed to 2022.2.post4.
Now I get another error.

RuntimeError: Cuda error: 304[cudaGraphicsGLRegisterBuffer(&s.cudaPosBuffer, s.glPosBuffer, cudaGraphicsRegisterFlagsWriteDiscard);]

Do you know what the cause is?

My PC is as follows.
win10
NVIDIA Tesla P40(v.518.03)&AMD FirePro W2100
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
![2023-12-14_025344](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/caad305a-6881-4289-ae0d-2b242cbae1d3)
![2023-12-14_025419](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/6fd02b6e-3b1f-45e8-b5f3-ba38de867a8a)
![2023-12-14_025438](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/121f54f4-49bf-4db1-818e-3cf210b92b38)

![2023-12-14_025429](https://github.com/dreamgaussian/dreamgaussian/assets/104999084/0680878d-92f7-469a-b753-44a016588366)

**Comment by ashawkey** [comment]
@ptyogi Hi, I have updated the code to support latest pymeshlab. The second error seems to be related to nvdiffrast, you may try using `force_cuda_rast=True`.

**Comment by ptyogi** [comment]
> @ptyogi Hi, I have updated the code to support latest pymeshlab. The second error seems to be related to nvdiffrast, you may try using `force_cuda_rast=True`.

@ashawkey thank you for your reply.
After updating, I used `force_cuda_rast=True` and it worked.
`python main.py --config configs/text.yaml prompt="a photo of an icecream" save_path=icecream force_cuda_rast=True`
Thank you very much for your cooperation!
